# WebApp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  minReadySeconds: 30
  template: # template do pod
    metadata:
      # pod não precisa de um nome
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
# Queue

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
    release: "0"
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1
