apiVersion: v1
kind: Service
metadata:
  # Service name
  name: fleetman-webapp
spec:
  # Pods represetados por esse Service
  # Service => network endpoint pra outros services ou uso externo (ex: browser)
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      # targetPort: 80
      nodePort: 30080 # deve ser maior que 30k
  # Tipos diferentes de services
  type: NodePort #outras opçoes: LoadBalancer ou ClusterIP
